#server.port: 8080

host: springboot-filestorage
port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/drunker
#    url: jdbc:postgresql://localhost:5432/drunker
    username: postgres
    password: root

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect