#server:
#  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drunker
    username: postgres
    password: root

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

services:
  filestorage-service:
    url: http://springboot-filestorage:8085