spring:
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/drunker
#    url: jdbc:postgresql://localhost:5432/drunker
    username: postgres
    password: root

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

  main.allow-bean-definition-overriding: true

services:
  filestorage-service:
    url: http://springboot-filestorage:8085
