#server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/drunker
    username: postgres
    password: root
#    driverClassName: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#    hibernate:
#      ddl-auto: validate



#  main:
#    banner-mode: off
#    allow-bean-definition-overriding: true